using System;
using System.ComponentModel.DataAnnotations;

namespace TimeManagementSystem.Server.Models
{
    public class RegisterModel
    {
        
        public string? Email { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string UserName { get; set; }

        public string Password { get; set; }

        public string? MiddleName { get; set; }
        public string? NameSuffix { get; set; }

        
        public string? EmailAddress { get; set; }

        [Required]
        public bool Active { get; set; }  // Assuming this is required and should be set during registration

        public string? MobileNo { get; set; }
        public string? ImmediateSuperior { get; set; }

        public string? ImmediateSuperiorCode { get; set; }

        public string? SelectedRole { get; set; }
        public string? AddressForeign { get; set; }

        [Required]
        public DateTime BirthDate { get; set; } // Assuming this is required

       
        public DateTime? DateHired { get; set; } // Assuming this is required

        public DateTime? DateSeparated { get; set; }

        // Updated MasterList 

       


       
        // EmployeeCode is generated by the backend, so it's not included here
        public int? EmploymentTypeId { get; set; }
        public int? GenderId { get; set; }
        public int? MaritalStatusId { get; set; }
        public int? DepartmentId { get; set; }  
        public int? PositionCodeId { get; set; }
        public int? TeamId { get; set; }
        public int? ModeOfSeparationId { get; set; }
        public int? EmployeeStatusId { get; set; }
    }
}